version: '2.1'
volumes:
  zwavejs2mqtt: {}
services:
  main:
    image: "zwavejs/zwavejs2mqtt:latest"
    ports:
      - "3000:3000"
      - "80:8091"
    volumes:
      - "zwavejs2mqtt:/usr/src/app/store"
    devices:
      - "/dev/ttyUSB0:/dev/zwave"
    privileged: true
    restart: always
    network_mode: host
