version: '2.1'
volumes:
  zwave-config:
    name: zwave-config
networks:
  zwave: {}
services:
  main:
    container_name: zwave-js-ui
    image: "zwavejs/zwave-js-ui:8.6.2"
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
    ports:
      - "3000:3000"
      - "80:8091"
    volumes:
      - "zwave-config:/usr/src/app/store"
    devices:
      - "/dev/ttyUSB0"
      - "/dev/ttyUSB1"
    privileged: true
    networks:
      - zwave
